### ISSUE TITLE
Messing up ongoing simulations by frantically pressing the simulate button

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#16]
When running a simulation, the GUI still allows the user to press the Simulate button and these requests are relayed to Django. This creates errors in the server terminal. This sometimes also messes up the first simulation so that it's unable to save the results. Any new simulations also fail after this.

**Comment by henhok** [comment]
2019-10-01 09:06:30,430 django.request ERROR    Internal Server Error: /simulate
Traceback (most recent call last):
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/henhok/cxsystem_testsuite/CxSystem2/CxGUI/CxFront/editor/views.py", line 56, in simulate
    CM.run()
  File "../../CxSystem.py", line 385, in run
    self.gather_result()
  File "../../CxSystem.py", line 1878, in gather_result
    self.save_output_data.save_to_file()
  File "../../save_data.py", line 70, in save_to_file
    os.makedirs(self.save_folder)
  File "/home/henhok/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/henhok/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './tests'
2019-10-01 09:06:30,432 django.server ERROR    "POST /simulate HTTP/1.1" 500 43818
