### ISSUE TITLE
GeNN suddenly not working anymore? 

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#20]
I didn't use GeNN while running NeCo paper simulations, but now that I try it I get: 

NotImplementedError: GeNN does not support assigning to the delay variable -- set the delay for all synapses (heterogeneous delays are not supported) as an argument to the Synapses initializer.

**Comment by Vafa-Andalibi** [comment]
Where is this delay defined ? It's in the namespace but where is it set? in physio? This is in CxSystem.py : 

```            
exec("%s.delay=%s['delay']" % (_dyn_syn_name, _dyn_syn_namespace_name) ) # set the delays
```

**Comment by henhok** [comment]
It's set in the physio config, yes.

**Comment by Vafa-Andalibi** [comment]
This is partially fixed in f17f43be6c566b93061af4ac3642c56c2867c3b2, needs a working GeNN environment for testing. Also some synapse models are not GeNN friendly which needs to be changed.

**Comment by sivanni** [comment]
This is about Genn, too. Tried to run pytest in isosisko (cpp ran nicely), and got:
/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2
 -  Current run filename suffix is: 20191210_1547031
 -  The system is running with euler integration method
 -  System parameter cluster_login_node not defined.
 -  System is going to be run using GeNN devices, Errors may rise if Brian2/Brian2GeNN/GeNN is not installed correctly or the limitations are not taken in to account.
 -  CxSystem is running on GeNN device
 -  Membrane voltages are not initialized.
 -  Default clock is set to 100. us
 -  simulation folder /opt3/CX2_wrkdir/sim_pytest
 -  CxSystem is running in local mode
Process spawned_CxSystem:
Traceback (most recent call last):
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/bui/cx_bui/editor/views.py", line 77, in cxspawner
    cm = Cx(anatomy, physiology)
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 305, in __init__
    self.configuration_executor()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 341, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 525, in set_runtime_parameters
    b2.set_device('genn', directory=self.workspace.get_simulation_folder().joinpath(self.suffix[1:]).as_posix())
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/devices/device.py", line 543, in set_device
    _do_set_device(device, build_on_run, **kwargs)
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/devices/device.py", line 550, in _do_set_device
    device = all_devices[device]
KeyError: 'genn'

**Comment by sivanni** [comment]
GeNN needs to be updated next time somebody uses it. There has been updates for synapses and variable checks in Brian2 versions after this issue was latest discussed. This is why I close this for now.
