### ISSUE TITLE
JSONified Rev2_step2 configs won't run thru GUI

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#23]
I used the config_file_converter to transform Markram model CSVs to JSONs and tried to run them thru the GUI.

SyntaxError: EOL while scanning string literal
2019-10-03 12:33:45,688 django.server ERROR    "POST /simulate HTTP/1.1" 500 100542
2019-10-03 12:34:53,757 django.request ERROR    Internal Server Error: /simulate
Traceback (most recent call last):
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/henhok/PycharmProjects/CxSystem2/CxGUI/CxFront/editor/views.py", line 54, in simulate
    received_data = eval(list(request._get_post().keys())[0].replace('false','0').replace('true','1'))
  File "<string>", line 1
    {"anatomy":{"params":{"runtime":"5*second","device":"Python","sys_mode":"local","scale":"1","grid_radius":"210*um","min_distance":"1*um","output_path_and_filename":"/home/henhok/sim_results/step2_viagui.gz","connections_saving_path_and_filename":"#","connections_loading_path_and_filename":"#","number_of_process":16,"default_clock":"0.1*ms","trials_per_config":1,"do_init_vms":1,"load_positions_only":0,"do_benchmark":0,"save_generated_video_input_flag":0,"multidimension_array_run":1,"profiling":0},"IN":[{"idx":0,"type":"VPM","number_of_neurons"

**Comment by Vafa-Andalibi** [comment]
I can't run the CxSystem with markram config directly from CxSystem. I'm using `Markram_config_file.csv` and both `Physiology_Parameter` and `Physiological_Parameters_for_calcium` but I'm bombarded with errors and I'm not sure whether I should fix them or they are from wrong config.

Which configs should I use?

**Comment by henhok** [comment]
This is probably related to issue #24 , i.e. connections_loading_path_and_filename can't be commented out in the GUI and CxSystem crashes (even if you don't use the connectivity data)

**Comment by Vafa-Andalibi** [comment]
Fixed in 8c4c19e635700093d025d68bb1e6b15698a3a56f
