### ISSUE TITLE
Has cluster run gone broken?

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#25]
CxSystem2 (branch frontend) doesn't seem to care about run_in_cluster flag anymore; starts running everything locally.

**Comment by Vafa-Andalibi** [comment]
This doesn't seem trivial to fix and needs discussion. The local CxSystem asks for password while running. If we want to implement it on a non-local GUI, it needs user-interaction and secure communication.

**Comment by Vafa-Andalibi** [comment]
cluster run batch job submission is now fixed in 9469c0b459bbd763c63b93e72e589d011d937fe0, but downloading the files should be done manually because they can't be downloaded to the server and from server to user's computer. Needs further discussion

**Comment by sivanni** [comment]
I wonder if my error is related to this:
(base) PS C:\Users\Simo\Laskenta\Git_Repos\CxSystem2> python .\gui_test.py
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 09, 2019 - 06:17:15
Django version 2.2.6, using settings 'CxFront.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2019-10-09 06:17:47,934 django.request ERROR    Internal Server Error: /simulate
Traceback (most recent call last):
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\CxGUI\CxFront\editor\views.py", line 72, in simulate
    if anatomy['params']['run_in_cluster'] == 1:
KeyError: 'run_in_cluster'
2019-10-09 06:17:47,936 django.server ERROR    "POST /simulate HTTP/1.1" 500 40238

**Comment by Vafa-Andalibi** [comment]
This is because the browser cache should be cleared to reload the new website after `git pull`.

**Comment by Vafa-Andalibi** [comment]
I'm closing now because `cluster-run` is significantly changed after the re-implementation for `workspace`, e.g. CxSystem is not cloned anymore remotely, there is no branch parameter and package should be installed remotely. Downloading the results can also be done using `cxscluster` command now.
