### ISSUE TITLE
pandas key error

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#27]
After launching simulation from gui, I get the following error. My local W10 machine.

PS C:\Users\Simo\Laskenta\Git_Repos\CxSystem2> python .\gui_test.py
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 10, 2019 - 10:24:32
Django version 2.2.6, using settings 'CxFront.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\Simo\Laskenta\Git_Repos\CxSystem2
 -  Current run filename suffix is: 20191010_10250627
 -  The system is running with euler integration method
 -  System parameter remote_branch not defined.
 -  CxSystem is running on Python device
 -  Membrane voltages are not initialized.
 -  Default clock is set to 100. us
 -  setting output path ...
Process spawned_CxSystem:
Traceback (most recent call last):
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\CxGUI\CxFront\editor\views.py", line 36, in CxSpawner
    cm =  Cx(anatomy, physiology)
  File "../..\CxSystem.py", line 236, in __init__
    self.configuration_executor()
  File "../..\CxSystem.py", line 268, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "../..\CxSystem.py", line 428, in set_runtime_parameters
    if parameter == correct_parameter_to_set and str(self.current_values_list[ParamIdx])[0] != '#':
  File "C:\Users\Simo\Miniconda3\lib\site-packages\pandas\core\series.py", line 1068, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 992, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 20

**Comment by Vafa-Andalibi** [comment]
This might be issue with the cached version of the GUI, or the old config files, or the old pandas, or wrong config files. Can you clear the browser cache for the GUI, run the latest pytest json files, and test again and report the results?

**Comment by henhok** [comment]
This issue emerged on my computer as well now. CSV runs fine, but after conversion to JSON and trying to run thru GUI, I get:

127.0.0.1 - - [07/Nov/2019 12:48:16] "POST /simulate HTTP/1.1" 200 -
/home/henhok/PycharmProjects/CxSystem2/cxsystem2
 -  Current run filename suffix is: 20191107_12482677
 -  The system is running with euler integration method
 -  System parameter remote_branch not defined.
 -  Brian Code Generator set to Numpy
 -  CxSystem is running on python device
 -  Membrane voltages are being randomly initialized.
 -  Default clock is set to 100. us
 -  The output of the simulation is saved at: /home/henhok/CxWorkspace/cobaeif_20191107_12482677/results.gz
Process spawned_CxSystem:
Traceback (most recent call last):
  File "/home/henhok/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/henhok/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/henhok/PycharmProjects/CxSystem2/cxsystem2/gui/cx_gui/editor/views.py", line 36, in CxSpawner
    cm =  Cx(anatomy, physiology)
  File "/home/henhok/PycharmProjects/CxSystem2/cxsystem2/core/cxsystem.py", line 227, in __init__
    self.configuration_executor()
  File "/home/henhok/PycharmProjects/CxSystem2/cxsystem2/core/cxsystem.py", line 258, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "/home/henhok/PycharmProjects/CxSystem2/cxsystem2/core/cxsystem.py", line 461, in set_runtime_parameters
    if parameter == correct_parameter_to_set and str(self.current_values_list[ParamIdx])[0] != '#':
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1068, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/henhok/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 992, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 26

**Comment by henhok** [comment]
I tested also that the JSONs go nicely through when doing just cxs.CxSystem(...).run(). Browser cache also probably not an issue as I ran things incognito.

**Comment by Vafa-Andalibi** [comment]
This is fixed apparently after installing the cxsystem2 in venv with recent pandas
