### ISSUE TITLE
Django fails when launched from command line

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#54]
Windows10, pulled from master.
(base) PS C:\Users\Simo\Laskenta\Git_Repos\CxSystem2> python .\gui_test.py
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Simo\Miniconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Simo\Miniconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\urls\resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\urls\resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Simo\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\cxsystem2\gui\cx_gui\cx_gui\urls.py", line 20, in <module>
    path('', include('editor.urls')),
  File "C:\Users\Simo\Miniconda3\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Simo\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\cxsystem2\gui\cx_gui\editor\urls.py", line 3, in <module>
    from . import views
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\cxsystem2\gui\cx_gui\editor\views.py", line 8, in <module>
    from cxsystem2.core.cxsystem import CxSystem as Cx
ModuleNotFoundError: No module named 'cxsystem2'

**Comment by Vafa-Andalibi** [comment]
The following minimal python should run the BUI (tested) on port 8888 without `ssl`:

``` python
from cxsystem2.core.cxsystem import CxSystem

cx = CxSystem()
cx.runGUI(ssl=False, port=8888)
```
