### ISSUE TITLE
Run in cluster fails

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#56]
Prompts credentials, but fails locally. pdb at line 387 has no effect either locally or remotely.

Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 30, 2019 - 12:55:39
Django version 2.2.6, using settings 'cx_gui.settings'
Starting development server at http://127.0.0.1:57403/
Quit the server with CTRL-BREAK.
Please enter your password for user svanni:
c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2
 -  Current run filename suffix is: 20191030_12560371
 -  The system is running with euler integration method
 -  System parameter remote_branch not defined.
 -  System parameter password not defined.
 -  Brian Code Generator set to Numpy
 -  CxSystem is running on python device
 -  Membrane voltages are not initialized.
 -  Default clock is set to 100. us
 -  setting output path ...
 -  CxSystem is running in local mode
 -  Creating an input based on the central 60 neurons ...
Process spawned_CxSystem:
Traceback (most recent call last):
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\gui\cx_gui\editor\views.py", line 36, in CxSpawner
    cm =  Cx(anatomy, physiology)
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\cxsystem.py", line 232, in __init__
    self.configuration_executor()
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\cxsystem.py", line 268, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\cxsystem.py", line 1885, in relay
    input_type_to_method_mapping[_input_type][2](self)
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\cxsystem.py", line 1723, in VPM
    self.min_distance, self.physio_config_df, network_center=net_center)
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\physiology_reference.py", line 77, in __init__
    self.output_neuron['namespace'] = neuron_parser(self.output_neuron, physio_config_df).output_namespace
  File "c:\users\simo\laskenta\git_repos\cxsystem2\cxsystem2\core\parameter_parser.py", line 387, in __init__
    variable_start_idx = self.physio_config_df['Variable'][self.physio_config_df['Variable'] == neuron_type_to_find].index[0]
  File "C:\Users\Simo\Miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 4280, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by Vafa-Andalibi** [comment]
I'm closing this because `cluster-run` had not been implemented with the new workspace paradigm at that point. There has been significant changes to `cluster-run` recently and it's tested. If you found issues with the `cluster-run` feel free to open another one.
