### ISSUE TITLE
COBAEIF giver error

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#73]
I am running is parallel one cpp device (step1) in another port in same browser. 
Even if I restart the server in new port, and Pytest runs nicely, for COBAEIF I get:
(CX2) sivanni@dx6-neuromancer:/opt3/CX2_wrkdir$ cxserver
Server configuration file not found, logging to console only
Server configuration file not found, logging to console only
Performing system checks...

System check identified no issues (0 silenced).
December 10, 2019 - 16:31:57
Django version 2.2.7, using settings 'cx_bui.settings'
Starting development server at http://127.0.0.1:46061/
Quit the server with CONTROL-C.
/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2
 -  Current run filename suffix is: 20191210_1632136
 -  The system is running with euler integration method
 -  simulation folder /home/sivanni/CxWorkspace/cobaeif
Traceback (most recent call last):
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/hpc/array_run.py", line 23, in <module>
    from cxsystem2.core import cxsystem as cx
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 25, in <module>
    import brian2 as b2
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/__init__.py", line 36, in <module>
    _check_dependencies()
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/__init__.py", line 18, in _check_dependencies
    import sympy
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/__init__.py", line 57, in <module>
    from .core import *
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/expr.py", line 6, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/evalf.py", line 28, in <module>
    from sympy.utilities.iterables import is_sequence
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/__init__.py", line 13, in <module>
    from .lambdify import lambdify
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 16, in <module>
    from sympy.utilities.decorator import doctest_depends_on
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/decorator.py", line 13, in <module>
    from sympy.utilities.runtests import DependencyError, SymPyDocTests, PyTestReporter
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/runtests.py", line 22, in <module>
    import pdb
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/pdb.py", line 136, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'

**Comment by sivanni** [comment]
With minor mod (no array, no VPM), I got probably the next error, which might be silly (gz vs gzip):
/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2
 -  Current run filename suffix is: 20191210_1638290
 -  The system is running with euler integration method
 -  System parameter cluster_login_node not defined.
 -  Brian Code Generator set to Numpy
 -  CxSystem is running on python device
 -  Membrane voltages are being randomly initialized.
 -  Default clock is set to 100. us
 -  simulation folder /home/sivanni/CxWorkspace/sv_small
 -  CxSystem is running in local mode
 -  Creating an input based on the central 60 neurons ...
 -  Neuron model is EIF 
 -  Customized VPM neuron in layer 0 initialized with 60 neurons.
 -  Neuron model is EIF 
 -  Customized SS neuron in layer 4 initialized with 3200 neurons.
 -  Neuron model is EIF 
 -  Customized BC neuron in layer 4 initialized with 800 neurons.
Process spawned_CxSystem:
Traceback (most recent call last):
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/bui/cx_bui/editor/views.py", line 77, in cxspawner
    cm = Cx(anatomy, physiology)
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 305, in __init__
    self.configuration_executor()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 341, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 1370, in synapse
    self.set_import_connections_path()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 570, in set_import_connections_path
    self.imported_connections = self.workspace.import_connections()
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/workspace_manager.py", line 92, in import_connections
    ' -  Compression method {} is not supported. Supported methods are gz, bz2 or pickle'.format(self.imported_connections_path.suffix)
AssertionError:  -  Compression method  is not supported. Supported methods are gz, bz2 or pickle

**Comment by Vafa-Andalibi** [comment]
I can't reproduce this and I need mere information. 
I just ran two instance of cobaeif with python and one with Cpp at the same time on isosisko. How can I reproduce this? 
Also, what's the environment you are running it on? 
Note that you don't need to run multiple instance of cxserver. Run all simulations in the same window or another window with the same port.

**Comment by Vafa-Andalibi** [comment]
I assume this is already fixed since it was also tested by Alex.
