### ISSUE TITLE
Array run gives error

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#77]
Running pytest example with background rate {0&5&10}*Hz gives:
/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2
 -  Current run filename suffix is: 20191211_1622021
 -  The system is running with euler integration method
 -  simulation folder /home/sivanni/CxPytestWorkspace/sim_pytest
Traceback (most recent call last):
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/hpc/array_run.py", line 23, in <module>
    from cxsystem2.core import cxsystem as cx
  File "/opt2/Laskenta_models_on_ssd/CxSystem2/cxsystem2/core/cxsystem.py", line 25, in <module>
    import brian2 as b2
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/__init__.py", line 36, in <module>
    _check_dependencies()
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/brian2/__init__.py", line 18, in _check_dependencies
    import sympy
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/__init__.py", line 57, in <module>
    from .core import *
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/expr.py", line 6, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/core/evalf.py", line 28, in <module>
    from sympy.utilities.iterables import is_sequence
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/__init__.py", line 13, in <module>
    from .lambdify import lambdify
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 16, in <module>
    from sympy.utilities.decorator import doctest_depends_on
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/decorator.py", line 13, in <module>
    from sympy.utilities.runtests import DependencyError, SymPyDocTests, PyTestReporter
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/site-packages/sympy/utilities/runtests.py", line 22, in <module>
    import pdb
  File "/opt2/Software/miniconda3/envs/CX2/lib/python3.7/pdb.py", line 136, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'

**Comment by Vafa-Andalibi** [comment]
Can you try this on a fresh python environment? I tried it on my computer and it completed the simulation with no issue.

**Comment by Vafa-Andalibi** [comment]
Given the newer issues which require array_run, I assume this is already fixed on your side.
